print("!Basic Calculator!")
a=int(input("enter first number:"))
b=int(input("enter second number:"))
print("Adition:",a+b)
print("substraction:",a-b)
print("multiplication:",a*b)
print("Division:",a/b)
print("modulus:",a%b)
print("Floor division",a//b)
print("power:",a**b)